CREATE TABLE IF NOT EXISTS carwash.services (
    id integer NOT NULL,
    service character varying NOT NULL,
    price integer NOT NULL,
    time_minutes integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE carwash.services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carwash.services_id_seq
    START WITH 1
    INCREMENT BY 1
    CACHE 1
);