CREATE TABLE IF NOT EXISTS carwash.orders (
    id integer NOT NULL,
    user_name character varying NOT NULL,
    time_issued timestamp NOT NULL,
    time_start timestamp NOT NULL,
    time_finish timestamp NOT NULL,
    is_finished boolean DEFAULT false NOT NULL,
    price integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE carwash.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carwash.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    CACHE 1
);