CREATE TABLE IF NOT EXISTS carwash.operations (
    id integer NOT NULL,
    order_id integer NOT NULL REFERENCES carwash.orders ON DELETE CASCADE,
    service_id integer NOT NULL REFERENCES carwash.services ON DELETE CASCADE,
    PRIMARY KEY (id)
);

ALTER TABLE carwash.operations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carwash.operations_id_seq
    START WITH 1
    INCREMENT BY 1
    CACHE 1
);